### PR TITLE
Add three default types and fix a iconImageView position bug

### PR DESCRIPTION
**Pull request by akring**
Just wish to make this project easier to use without much customize,it's ok to abandon this PR if you think it's not appropriate.

Best wishes!

### CODE REVIEW

**Comment by Jon-Schneider** [comment]
Thanks for the pull request, akring!

We originally removed multiple notification types when paring down TSMessage's functionality into the much simpler feature-set that you see LNRSimpleNotifications because we thought that multiple notification types are not really necessary in 95% of applications. While they're not a feature we'd want to rule out in the future, for the moment we're committed to keeping the feature set of LNRSimpleNotifications as minimal as possible.

If you want to submit a new pull request with just your iconImageView fix I'd be happy to look at it.

**Comment by akring** [comment]
OK,I will check it later

**Comment by akring** [comment]
just modify `LNRSimpleNotificationView.swift` with:

```swift
let yPosition = self.position == LNRNotificationPosition.Top ? round((kStatusBarHeight+height) / 2.0) : round((height) / 2.0)
self.iconImageView.center = CGPoint(x: self.iconImageView.center.x, y: yPosition)
```

This will fix the position for the iconImageView when there just one line text for notification's `body` .It's too high like that:

screen shot

My Xcode crashed when I tried to update it,so I can't make a pull request right now,maybe you guys can fix this:)

**Comment by Jon-Schneider** [comment]
Implemented.

Thanks!

**Comment by Jon-Schneider** [comment]
Hey akring , I just made an update to the pod, version 0.3.0, that might cover your use case. Now rather than using a singleton which can only have one theme at a time to handle notifications,, you can now create multipole LNRNotificationManager instances, each with a different theme.

**Comment by akring** [comment]
Great job man!I will try it later,thanks:)

**Pull request closed without merging**
